package world.best.musicplayer.utils.files.tag;

/**
 * This is the exception that is always generated by any class in these
 * packages.
 */
public class TagException extends Exception
{
    /**
     * Creates a new TagException datatype.
     */
    public TagException()
    {
    }

    /**
     * Creates a new TagException datatype.
     *
     * @param ex the cause.
     */
    public TagException(Throwable ex)
    {
        super(ex);
    }

    /**
     * Creates a new TagException datatype.
     *
     * @param msg the detail message.
     */
    public TagException(String msg)
    {
        super(msg);
    }

    /**
     * Creates a new TagException datatype.
     *
     * @param msg the detail message.
     * @param ex  the cause.
     */
    public TagException(String msg, Throwable ex)
    {
        super(msg, ex);
    }
}